version: '3.5'

networks:

  net:
    driver: bridge
    name: cv

services:

  api:
    image: cv_api
    build:
      context: src/api/api
      dockerfile: Dockerfile

# to access from docker host
#   ports:
#     - '5000:80'

    networks:
      - net

  web:
    image: cv_web
    build:
      context: src/web
      dockerfile: Dockerfile

# to access from docker host
#   ports:
#     - '80:80'

    networks:
      - net

  pdf:
    image: cv_pdf
    build:
      context: src/pdf
      dockerfile: Dockerfile
    networks:
      - net
    volumes:
      - ./pdf:/root
    depends_on:
      - 'api'
      - 'web'
    command: [
      'wkhtmltopdf',
      '--footer-html', 'http://cv_web_1/footer',
      '--javascript-delay', '750',
      '--debug-javascript',
      '--margin-bottom', '3cm',
      '--margin-left', '1cm',
      '--margin-right', '1cm',
      '--margin-top', '1cm',
      'http://cv_web_1/cv',
      '/root/cv.pdf'
    ]
